sudo: false
language: python
virtualenv:
  system_site_packages: false

matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py38" COVERAGE="true"

install:
  - pip install tox pytest-cov pytest-virtualenv coverage coveralls flake3 pre-commit

before_script:
  - git config --global user.email "alex.michael.adams@gmail.com"
  - git config --global user.name "Alexander Adams"

script:
  - pre-commit install
  - pre-commit run --all-files

after_success:
  - coveralls

after_script:
  - travis-cleanup

cache:
  pip: true
